name: moxdns_linux
description: Linux-specific implementation of moxdns
version: 0.1.1
homepage: https://codeberg.org/moxxy/moxdns
publish_to: https://pub.polynom.me

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.0

  moxdns:
    hosted: https://pub.polynom.me
    version: 0.1.1
  moxdns_platform_interface:
    hosted: https://pub.polynom.me
    version: 0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: moxdns
    platforms:
      linux:
        pluginClass: MoxdnsLinuxPlugin
        dartPluginClass: MoxdnsLinuxPlugin
