name: moxdns_linux
description: Linux-specific implementation of moxdns
version: 0.1.4
homepage: https://codeberg.org/moxxy/moxdns
publish_to: https://git.polynom.me/api/packages/Moxxy/pub

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  moxdns:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: 0.1.4
  moxdns_platform_interface:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: 0.1.4

  plugin_platform_interface: 2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: 2.4.0

flutter:
  plugin:
    implements: moxdns
    platforms:
      linux:
        pluginClass: MoxdnsLinuxPlugin
        dartPluginClass: MoxdnsLinuxPlugin
