name: moxdns
description: A simple wrapper over platform native DNS methods
version: 0.1.0
homepage:

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: moxdns_android
  
dependencies:
  flutter:
    sdk: flutter

  moxdns_platform_interface:
    path: ../moxdns_platform_interface
  moxdns_android:
    path: ../moxdns_android


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
