name: moxdns
description: A simple wrapper over platform native DNS methods
version: 0.1.1
homepage: https://codeberg.org/moxxy/moxdns
publish_to: https://pub.polynom.me

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: moxdns_android
      linux:
        default_package: moxdns_linux
 
dependencies:
  flutter:
    sdk: flutter

  moxdns_platform_interface:
    hosted: https://pub.polynom.me
    version: 0.1.1
  moxdns_android:
    hosted: https://pub.polynom.me
    version: 0.1.1
  moxdns_linux:
    hosted: https://pub.polynom.me
    version: 0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
