name: moxdns_platform_interface
description: Platform definitions for moxdns
version: 0.1.0
homepage:

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
