name: moxdns_platform_interface
description: Platform definitions for moxdns
homepage: https://codeberg.org/moxxy/moxdns
version: 0.1.5
publish_to: https://git.polynom.me/api/packages/Moxxy/pub

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: 2.4.0
