name: moxdns_android
description: Android-specific implementation of moxdns
version: 0.1.0
homepage:

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.0

  moxdns:
    path: ../moxdns
  moxdns_platform_interface:
    path: ../moxdns_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.polynom.moxdns_android
        pluginClass: MoxdnsAndroidPlugin
        dartPluginClass: MoxdnsAndroidPlugin
